type = "directrequest"
schemaVersion = 1
name = "tusd adapter job spec"
contractAddress = ""
observationSource = """
    ds          [type="http" method=GET url=""]
    ds_parse    [type="jsonparse" path="result"]
    ds_multiply [type="multiply" times=10000]

    ds -> ds_parse -> ds_multiply
"""
